// Plan catalogue sourced from the subscription plan sheet (Basic / Gold / Platinum).
export const CURRENT_PLAN_ID = 'gold';

export const plans = [
  {
    id: 'basic',
    name: 'Basic',
    tagline: 'Starter Plan',
    duration: '1 Month Plan',
    months: 1,
    price: 499,
    totalPrice: null,
    saveBadge: null,
    serviceCount: 10,
    features: [
      { name: 'Export Promotional Meetings', tag: 'Full' },
      { name: 'FEED Card', tag: 'Full' },
      { name: 'Know Your Schemes', tag: 'Full' },
      { name: 'Krushi Yeva Jayate', tag: 'Full' },
      { name: 'Loans & Finance', tag: 'Full' },
      { name: 'My Farm', tag: '3 Farms' },
      { name: 'My Market', tag: 'Full' },
      { name: 'My Products', tag: '5 Products' },
      { name: 'Safe Mission', tag: 'Full' },
      { name: 'Trade Fairs', tag: 'Full' },
    ],
  },
  {
    id: 'gold',
    name: 'Gold',
    tagline: 'Popular Plan',
    duration: '3 Months Plan',
    months: 3,
    price: 1999,
    totalPrice: 5997,
    saveBadge: 'Save with bundle',
    popular: true,
    serviceCount: 14,
    features: [
      { name: 'Export Promotional Meetings', tag: 'Full' },
      { name: 'FEED Card', tag: 'Full' },
      { name: 'FEED World', tag: 'Full' },
      { name: 'Know Your Schemes', tag: 'Full' },
      { name: 'Krushi Yeva Jayate', tag: 'Full' },
      { name: 'Loans & Finance', tag: 'Full' },
      { name: 'My Business', tag: 'Full' },
      { name: 'My Education', tag: 'Full' },
      { name: 'My Farm', tag: 'Unlimited' },
      { name: 'My Market', tag: 'Full' },
      { name: 'My Products', tag: '20 Products' },
      { name: 'My Tools', tag: 'Full' },
      { name: 'Safe Mission', tag: 'Full' },
      { name: 'Trade Fairs', tag: 'Full' },
    ],
  },
  {
    id: 'platinum',
    name: 'Platinum',
    tagline: 'Complete Plan',
    duration: '12 Months Plan',
    months: 12,
    price: 4999,
    totalPrice: 59988,
    saveBadge: 'Best Value',
    bestChoice: true,
    serviceCount: 16,
    features: [
      { name: 'Export Promotional Meetings', tag: 'Full' },
      { name: 'FEED Card', tag: 'Full' },
      { name: 'FEED World', tag: 'Full' },
      { name: 'Know Your Schemes', tag: 'Full' },
      { name: 'Krushi Yeva Jayate', tag: 'Full' },
      { name: 'Loans & Finance', tag: 'Full' },
      { name: 'My Business', tag: 'Full' },
      { name: 'My Education', tag: 'Full' },
      { name: 'My Exports', tag: 'Full Access' },
      { name: 'My Farm', tag: 'Unlimited' },
      { name: 'My Market', tag: 'Full' },
      { name: 'My FPO / Organization', tag: 'Full' },
      { name: 'My Products', tag: 'Unlimited' },
      { name: 'My Tools', tag: 'Full' },
      { name: 'Safe Mission', tag: 'Full' },
      { name: 'Trade Fairs', tag: 'Full' },
    ],
  },
];

export const formatINR = (value) => value.toLocaleString('en-IN');
